# Preface {-}

Chapter \@ref(ch:calendar-vis) has been conditionally accepted by the *Journal of Computational and Graphical Statistics* for the second-round revision. It has won the ASA Statistical Graphics Student Paper Award and the ACEMS Business Analytics Prize in 2018. Chapter \@ref(ch:tsibble) has been tentatively accepted and resubmitted to the *Journal of Computational and Graphical Statistics*. The accompanying R package **tsibble** has won the John Chambers Statistical Software Award in 2019. Chapter \@ref(ch:mists) is yet to be submitted.

### Open and reproducible research {-}

This thesis is written in R Markdown [@rmarkdown] with **bookdown** [@bookdown]. The online version of this thesis is hosted at <https://thesis.earo.me>, powered by [Netlify](http://netlify.com). All materials (including the data sets and source files) required to reproduce this document can be found at the Github repository <https://github.com/earowang/thesis>.

### License {-}

<center>
<i class="fab fa-creative-commons fa-2x"></i><i class="fab fa-creative-commons-by fa-2x"></i><i class="fab fa-creative-commons-sa fa-2x"></i>
</center>

This work is licensed under a [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-nc-sa/4.0/).

The code used in this document is available under the [MIT license](https://opensource.org/licenses/MIT).

\clearpage\pagenumbering{arabic}\setcounter{page}{0}
