# Conclusion and future plans {#ch:conclusion}

The three papers assembled in this thesis, share a common theme of exploratory analysis for temporal data using tidy tools. Chapter \@ref(ch:calendar-vis), "Calendar-based graphics for visualizing people's daily schedules", described a new calendar-based display. Chapter \@ref(ch:tsibble), "A new tidy data structure to support exploration and modeling of temporal data", proposed a new temporal data abstraction. Chapter \@ref(ch:mists), "", demystified missing data in time. These papers are bundled with software. In this conclusion, I will briefly summarise each package and their impact, and discuss the future directions of my research.

## Software development

```{r software-impact}
library(cranlogs)
sugrrants_dl <- cran_downloads("sugrrants", from = "2017-07-28")
tsibble_dl <- cran_downloads("tsibble", from = "2018-01-09")
```

A particular emphasis of this thesis is translating research methodologies in the form of open source R packages: **sugrrants**, **tsibble**, and **mists**.

### sugrrants

The **sugrrants** package implements the idea of displaying data in the familiar calendar style in the `frame_calendar()` and `facet_calendar()`. The research article, a shorter version of Chapter \@ref(ch:calendar-vis), has been awarded the best student paper prize from ASA Sections on Statistical Computing and Statistical Graphics and ACEMS Business Analytics in 2018. There have been a grand total of `r format(sum(sugrrants_dl$count), big.mark = ",")` downloads from the RStudio mirror (one of 90 CRAN mirrors) dating from 2017-07-28 to `r Sys.Date()`; and it has been starred 47 times on Github so far. The homepage at <https://pkg.earo.me/sugrrants> contains detailed documentation and a vignette on `frame_calendar()`.

### tsibble

The **tsibble** package provides a data infrastructure and a domain specific language in R for representing and manipulating tidy temporal data. This package is aimed for the fundamental architecture that other temporal tools will be built upon. For example, a new suite of time series analysis packages, titled ["tidyverts"](https://github.com/tidyverts), have been developed for the new "tsibble" object. The **tsibble** package has won 2019 John Chambers Statistical Software Award from ASA Sections on Statistical Computing and Statistical Graphics. It has been downloaded `r format(sum(tsibble_dl$count), big.mark = ",")` times from the RStudio mirror since it landed on CRAN on 2018-01-09; and it has received 234 stars on Github. These metrics are the indicators of my research impact, the recognition by professionals, and the uptakes by users. The website (<https://tsibble.tidyverts.org>) includes full documentation and three vignettes about the package usage.

### mists

The **mists** package aims at exploring missing values for temporal data both analytically and graphically. It implements a compact abstraction for efficiently indexing missing data in time, along with numerical and visual methods. It also brings missing data polishing techniques into live. The Github repository has received 22 stars, but the package is not on CRAN yet. The documentation site is available at <https://pkg.earo.me/mists>. 

## Future work

### Process for generating missing data in time

Missing values in cross-sectional data are typically characterised by the overall, row-wise, and column-wise missings. Neither, however, captures the dynamics in temporal data. How to characterise temporal missingness receives little research. A good metric of such could possibly shed lights on the process for generating and imputing missing data in time.

I will expand on Chapter \@ref(ch:mists), to develop systematic missing data generating processes. Generating temporal missingness can be decomposed into two steps: (1) to inject point missings along indices and (2) to simulate the corresponding lengths.

### Visual methods for temporal data of nesting and crossing interactions

A collection of time series are often structured in a way that allows nesting and crossing interactions [@fpp]. For example, a manufacturing company can add up every store's sales by region, by state and by country, which gives a strictly hierarchical time series; alternatively, they can gather the sales based on common attributes such as store, brand, price range and so forth, which leads to a crossed configuration. Nesting is a special case of crossing, with parent-children relations involved. Temporal information such as date-times is also intrinsically hierarchical, seconds nested within minutes, hours, and etc. The new tsibble structure has the neat capability of supporting these structural embeddings.

Numerous nesting and crossing combinations can yield unwieldy plots, in many of which an abundance of information are possibly buried. Focus-plus-context visualisation with interactivity comes to rescue. Dual contexts, structurally informative subjects and time, provide the source and visual clues for elegant navigation. Interactions on contextual plots control what to be visualised in the main plots, that form our focuses. Many kinds of visual displays can be generated to progressively build a richer data picture through guided or self explorations.
